name: Analisis de código con pylint

on: pull_request
  
jobs:
  test:
    name: Analizar código con pylint
    runs-on: ubuntu-latest
    permissions:
      security-events: write 

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Ejecutar análisis de código
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
